# .github/workflows/tests.yml
name: Tests
on: push
jobs:
  allnox:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["2.7", "3.5", "3.6", "3.7", "3.8"]
        include:
          # add a variable for reports + doc publish
          - os: ubuntu-latest
            python-version: "3.7"
            name_suffix: "+ publish doc and reports"
    name: Run all tests on OS ${{ matrix.os }} and python ${{ matrix.python-version }} ${{ matrix.name_suffix }}
    runs-on: ${{ matrix.os }}
    steps:
      # 1) Checkout a copy of the repo
      - name: Checkout code
        uses: actions/checkout@v2
      # 2) Setup python version 3.8
      - name: Install python 3.7 for nox
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      # 3) Add Conda to PATH
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      # 4) Install nox
      - name: Install noxfile requirements
        run: pip install -r noxfile-requirements.txt
      # 5) Run nox tests
      - name: Run tests on python ${{ matrix.python-version }}
        run: nox -s tests-${{ matrix.python-version }}
      # 6) Publish the doc, test reports and coverage reports
      # - name: Publish documentation, tests and coverage reports
      #  run: nox -s publish
