# .github/workflows/tests.yml
name: Build
on: push
jobs:
  allnox:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # , macos-latest, windows-latest]
        # python-version: ["2.7", "3.5", "3.6", "3.7", "3.8"]
        include:
          # add a variable for reports + doc publish
          - os: ubuntu-latest
#            python-version: "3.7"
            name_suffix: "+ publish doc and reports"
    name: Run all tests on OS ${{ matrix.os }} ${{ matrix.name_suffix }} # and python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      # 1) Checkout a copy of the repo
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # so that gh-deploy works
      # 2) Setup python version 3.8
#      - name: Install python 3.7 for nox
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.7
#          architecture: x64
      # 2) Add Conda to PATH
#      - name: Add conda to system path
#        run: |
#          # $CONDA is an environment variable pointing to the root of the miniconda directory
#          echo $CONDA/bin >> $GITHUB_PATH
      # 2) Setup conda
      - name: Install conda v3.7
        uses: conda-incubator/setup-miniconda@v2
        with:
          # auto-update-conda: true
          python-version: 3.7
          activate-environment: noxenv
      - name: Conda info init
        shell: bash -l {0}  # so that conda works
        run: conda info
      - name: Conda list init
        shell: bash -l {0}  # so that conda works
        run: conda list
      # 3) Install nox
      - name: Install noxfile requirements
        shell: bash -l {0}  # so that conda works
        run: pip install -r noxfile-requirements.txt
      # 4) conda list
      - name: Conda list 2
        shell: bash -l {0}  # so that conda works
        run: conda list
      # 5) Run nox tests
      - name: Run tests # on python ${{ matrix.python-version }}
        shell: bash -l {0}  # so that conda works
        run: nox -s tests-3.7  #-${{ matrix.python-version }}
      # 6) Publish the doc and test reports
      - name: Publish documentation, tests and coverage reports
        if: startsWith(matrix.os,'ubuntu')
        shell: bash -l {0}  # so that conda works
        run: nox -s publish
      # 7) Publish coverage report
      - name: Create codecov.yaml with correct paths
        shell: bash
        run: |
          cat << EOF > codecov.yml
          # codecov.yml
          fixes:
            - "/home/runner/work/smarie/python-makefun/::" # Correct paths
          EOF
      - name: Make codecov.yaml available in artifacts for debugging
        uses: actions/upload-artifact@v1
        with:
          name: codecov configuration
          path: codecov.yml
      - name: Publish coverage report
        # run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./.coverage
